/*
 * Copyright (c) 2025. Joe Paquette
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/**
 * This file is generated from a FHIR CodeSystem definition.
 * DO NOT make any modifications!
 *
 * MapTargetListModeEnum Module
 *
 * CodeSystem.url: http://hl7.org/fhir/map-target-list-mode
 * CodeSystem.name: MapTargetListMode
 * CodeSystem.description: If field is a list, how to manage the production.
 * CodeSystem.version: 4.0.1
 * CodeSystem.caseSensitive: true
 *
 * For questions, suggestions, or bugs, please open an issue at [GitHub ts-fhir-datamodels/issues](https://github.com/Paqrat76/ts-fhir-datamodels/issues).
 *
 * @packageDocumentation
 */

import {
  fhirCode,
  FhirCodeDefinition,
  IFhirCodeDefinition,
  IFhirCodeEnum,
  InvalidCodeError,
} from '@paq-ts-fhir/fhir-core';

/**
 * FHIR CodeSystem: MapTargetListModeEnum
 *
 * @remarks
 * This class is a "pseudo-enumeration" of code values having FHIR code properties.
 *
 * @category CodeSystems
 * @see [FHIR CodeSystem MapTargetListMode](http://hl7.org/fhir/map-target-list-mode)
 */
export class MapTargetListModeEnum implements IFhirCodeEnum {
  public static readonly FIRST = new FhirCodeDefinition(
    'FIRST',
    'first',
    'http://hl7.org/fhir/map-target-list-mode',
    'First',
    'when the target list is being assembled, the items for this rule go first. If more than one rule defines a first item (for a given instance of mapping) then this is an error.',
  );
  public static readonly SHARE = new FhirCodeDefinition(
    'SHARE',
    'share',
    'http://hl7.org/fhir/map-target-list-mode',
    'Share',
    'the target instance is shared with the target instances generated by another rule (up to the first common n items, then create new ones).',
  );
  public static readonly LAST = new FhirCodeDefinition(
    'LAST',
    'last',
    'http://hl7.org/fhir/map-target-list-mode',
    'Last',
    'when the target list is being assembled, the items for this rule go last. If more than one rule defines a last item (for a given instance of mapping) then this is an error.',
  );
  public static readonly COLLATE = new FhirCodeDefinition(
    'COLLATE',
    'collate',
    'http://hl7.org/fhir/map-target-list-mode',
    'Collate',
    're-use the first item in the list, and keep adding content to it.',
  );

  // NULL added to help check for non-existent value
  public static readonly NULL = new FhirCodeDefinition('NULL', `null`);

  /**
   * @returns an IFhirCodeDefinition[] containing the enumeration of code system code definitions
   */
  values(): IFhirCodeDefinition[] {
    return [
      MapTargetListModeEnum.FIRST,
      MapTargetListModeEnum.SHARE,
      MapTargetListModeEnum.LAST,
      MapTargetListModeEnum.COLLATE,
      MapTargetListModeEnum.NULL
    ];
  }

  /**
   * Converts a given FHIR code into its corresponding FHIR code definition.
   *
   * @param {fhirCode | undefined} code - The FHIR code to be converted. If undefined, an error will be thrown.
   * @returns {IFhirCodeDefinition} The FHIR code definition corresponding to the provided code.
   * @throws {@link InvalidCodeError} for undefined or invalid code value
   */
  fromCode(code: fhirCode | undefined): IFhirCodeDefinition {
    if (code === undefined) {
      throw new InvalidCodeError(`The provided 'code' value is undefined`);
    } else if (MapTargetListModeEnum.FIRST.code === code) {
      return MapTargetListModeEnum.FIRST;
    } else if (MapTargetListModeEnum.SHARE.code === code) {
      return MapTargetListModeEnum.SHARE;
    } else if (MapTargetListModeEnum.LAST.code === code) {
      return MapTargetListModeEnum.LAST;
    } else if (MapTargetListModeEnum.COLLATE.code === code) {
      return MapTargetListModeEnum.COLLATE;
    } else if (MapTargetListModeEnum.NULL.code === code) {
      return MapTargetListModeEnum.NULL;
    } else {
      throw new InvalidCodeError(`Unknown MapTargetListModeEnum 'code' value '${code}'`);
    }
  }
}
