/*
 * Copyright (c) 2025. Joe Paquette
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/**
 * This file is generated by the FHIR Data Model Generator.
 * DO NOT make any modifications!
 * 
 * parsable-resource-map.ts Module
 *
 * For questions, suggestions, or bugs, please open an issue at [GitHub ts-fhir-datamodels/issues](https://github.com/Paqrat76/ts-fhir-datamodels/issues).
 *
 * @packageDocumentation
 */

import { Resource, ParsableResource } from '@paq-ts-fhir/fhir-core';
import { Account } from './Account';
import { ActivityDefinition } from './ActivityDefinition';
import { AdverseEvent } from './AdverseEvent';
import { AllergyIntolerance } from './AllergyIntolerance';
import { Appointment } from './Appointment';
import { AppointmentResponse } from './AppointmentResponse';
import { AuditEvent } from './AuditEvent';
import { Basic } from './Basic';
import { Binary } from './Binary';
import { BiologicallyDerivedProduct } from './BiologicallyDerivedProduct';
import { BodyStructure } from './BodyStructure';
import { Bundle } from './Bundle';
import { CapabilityStatement } from './CapabilityStatement';
import { CarePlan } from './CarePlan';
import { CareTeam } from './CareTeam';
import { CatalogEntry } from './CatalogEntry';
import { ChargeItem } from './ChargeItem';
import { ChargeItemDefinition } from './ChargeItemDefinition';
import { Claim } from './Claim';
import { ClaimResponse } from './ClaimResponse';
import { ClinicalImpression } from './ClinicalImpression';
import { CodeSystem } from './CodeSystem';
import { Communication } from './Communication';
import { CommunicationRequest } from './CommunicationRequest';
import { CompartmentDefinition } from './CompartmentDefinition';
import { Composition } from './Composition';
import { ConceptMap } from './ConceptMap';
import { Condition } from './Condition';
import { Consent } from './Consent';
import { Contract } from './Contract';
import { Coverage } from './Coverage';
import { CoverageEligibilityRequest } from './CoverageEligibilityRequest';
import { CoverageEligibilityResponse } from './CoverageEligibilityResponse';
import { DetectedIssue } from './DetectedIssue';
import { Device } from './Device';
import { DeviceDefinition } from './DeviceDefinition';
import { DeviceMetric } from './DeviceMetric';
import { DeviceRequest } from './DeviceRequest';
import { DeviceUseStatement } from './DeviceUseStatement';
import { DiagnosticReport } from './DiagnosticReport';
import { DocumentManifest } from './DocumentManifest';
import { DocumentReference } from './DocumentReference';
import { EffectEvidenceSynthesis } from './EffectEvidenceSynthesis';
import { Encounter } from './Encounter';
import { Endpoint } from './Endpoint';
import { EnrollmentRequest } from './EnrollmentRequest';
import { EnrollmentResponse } from './EnrollmentResponse';
import { EpisodeOfCare } from './EpisodeOfCare';
import { EventDefinition } from './EventDefinition';
import { Evidence } from './Evidence';
import { EvidenceVariable } from './EvidenceVariable';
import { ExampleScenario } from './ExampleScenario';
import { ExplanationOfBenefit } from './ExplanationOfBenefit';
import { FamilyMemberHistory } from './FamilyMemberHistory';
import { Flag } from './Flag';
import { Goal } from './Goal';
import { GraphDefinition } from './GraphDefinition';
import { Group } from './Group';
import { GuidanceResponse } from './GuidanceResponse';
import { HealthcareService } from './HealthcareService';
import { ImagingStudy } from './ImagingStudy';
import { Immunization } from './Immunization';
import { ImmunizationEvaluation } from './ImmunizationEvaluation';
import { ImmunizationRecommendation } from './ImmunizationRecommendation';
import { ImplementationGuide } from './ImplementationGuide';
import { InsurancePlan } from './InsurancePlan';
import { Invoice } from './Invoice';
import { Library } from './Library';
import { Linkage } from './Linkage';
import { List } from './List';
import { Location } from './Location';
import { Measure } from './Measure';
import { MeasureReport } from './MeasureReport';
import { Media } from './Media';
import { Medication } from './Medication';
import { MedicationAdministration } from './MedicationAdministration';
import { MedicationDispense } from './MedicationDispense';
import { MedicationKnowledge } from './MedicationKnowledge';
import { MedicationRequest } from './MedicationRequest';
import { MedicationStatement } from './MedicationStatement';
import { MedicinalProduct } from './MedicinalProduct';
import { MedicinalProductAuthorization } from './MedicinalProductAuthorization';
import { MedicinalProductContraindication } from './MedicinalProductContraindication';
import { MedicinalProductIndication } from './MedicinalProductIndication';
import { MedicinalProductIngredient } from './MedicinalProductIngredient';
import { MedicinalProductInteraction } from './MedicinalProductInteraction';
import { MedicinalProductManufactured } from './MedicinalProductManufactured';
import { MedicinalProductPackaged } from './MedicinalProductPackaged';
import { MedicinalProductPharmaceutical } from './MedicinalProductPharmaceutical';
import { MedicinalProductUndesirableEffect } from './MedicinalProductUndesirableEffect';
import { MessageDefinition } from './MessageDefinition';
import { MessageHeader } from './MessageHeader';
import { MolecularSequence } from './MolecularSequence';
import { NamingSystem } from './NamingSystem';
import { NutritionOrder } from './NutritionOrder';
import { Observation } from './Observation';
import { ObservationDefinition } from './ObservationDefinition';
import { OperationDefinition } from './OperationDefinition';
import { OperationOutcome } from './OperationOutcome';
import { Organization } from './Organization';
import { OrganizationAffiliation } from './OrganizationAffiliation';
import { Parameters } from './Parameters';
import { Patient } from './Patient';
import { PaymentNotice } from './PaymentNotice';
import { PaymentReconciliation } from './PaymentReconciliation';
import { Person } from './Person';
import { PlanDefinition } from './PlanDefinition';
import { Practitioner } from './Practitioner';
import { PractitionerRole } from './PractitionerRole';
import { Procedure } from './Procedure';
import { Provenance } from './Provenance';
import { Questionnaire } from './Questionnaire';
import { QuestionnaireResponse } from './QuestionnaireResponse';
import { RelatedPerson } from './RelatedPerson';
import { RequestGroup } from './RequestGroup';
import { ResearchDefinition } from './ResearchDefinition';
import { ResearchElementDefinition } from './ResearchElementDefinition';
import { ResearchStudy } from './ResearchStudy';
import { ResearchSubject } from './ResearchSubject';
import { RiskAssessment } from './RiskAssessment';
import { RiskEvidenceSynthesis } from './RiskEvidenceSynthesis';
import { Schedule } from './Schedule';
import { SearchParameter } from './SearchParameter';
import { ServiceRequest } from './ServiceRequest';
import { Slot } from './Slot';
import { Specimen } from './Specimen';
import { SpecimenDefinition } from './SpecimenDefinition';
import { StructureDefinition } from './StructureDefinition';
import { StructureMap } from './StructureMap';
import { Subscription } from './Subscription';
import { Substance } from './Substance';
import { SubstanceNucleicAcid } from './SubstanceNucleicAcid';
import { SubstancePolymer } from './SubstancePolymer';
import { SubstanceProtein } from './SubstanceProtein';
import { SubstanceReferenceInformation } from './SubstanceReferenceInformation';
import { SubstanceSourceMaterial } from './SubstanceSourceMaterial';
import { SubstanceSpecification } from './SubstanceSpecification';
import { SupplyDelivery } from './SupplyDelivery';
import { SupplyRequest } from './SupplyRequest';
import { Task } from './Task';
import { TerminologyCapabilities } from './TerminologyCapabilities';
import { TestReport } from './TestReport';
import { TestScript } from './TestScript';
import { ValueSet } from './ValueSet';
import { VerificationResult } from './VerificationResult';
import { VisionPrescription } from './VisionPrescription';

/**
 * PARSABLE_RESOURCE_MAP
 *
 * @remarks
 * Map of all parsable Resources where the key is the name of the Resource and the value is its ParsableResource<Resource> class.
 *
 * @internal
 */
export const PARSABLE_RESOURCE_MAP = new Map<string, ParsableResource<Resource>>();
PARSABLE_RESOURCE_MAP.set('Account', Account);
PARSABLE_RESOURCE_MAP.set('ActivityDefinition', ActivityDefinition);
PARSABLE_RESOURCE_MAP.set('AdverseEvent', AdverseEvent);
PARSABLE_RESOURCE_MAP.set('AllergyIntolerance', AllergyIntolerance);
PARSABLE_RESOURCE_MAP.set('Appointment', Appointment);
PARSABLE_RESOURCE_MAP.set('AppointmentResponse', AppointmentResponse);
PARSABLE_RESOURCE_MAP.set('AuditEvent', AuditEvent);
PARSABLE_RESOURCE_MAP.set('Basic', Basic);
PARSABLE_RESOURCE_MAP.set('Binary', Binary);
PARSABLE_RESOURCE_MAP.set('BiologicallyDerivedProduct', BiologicallyDerivedProduct);
PARSABLE_RESOURCE_MAP.set('BodyStructure', BodyStructure);
PARSABLE_RESOURCE_MAP.set('Bundle', Bundle);
PARSABLE_RESOURCE_MAP.set('CapabilityStatement', CapabilityStatement);
PARSABLE_RESOURCE_MAP.set('CarePlan', CarePlan);
PARSABLE_RESOURCE_MAP.set('CareTeam', CareTeam);
PARSABLE_RESOURCE_MAP.set('CatalogEntry', CatalogEntry);
PARSABLE_RESOURCE_MAP.set('ChargeItem', ChargeItem);
PARSABLE_RESOURCE_MAP.set('ChargeItemDefinition', ChargeItemDefinition);
PARSABLE_RESOURCE_MAP.set('Claim', Claim);
PARSABLE_RESOURCE_MAP.set('ClaimResponse', ClaimResponse);
PARSABLE_RESOURCE_MAP.set('ClinicalImpression', ClinicalImpression);
PARSABLE_RESOURCE_MAP.set('CodeSystem', CodeSystem);
PARSABLE_RESOURCE_MAP.set('Communication', Communication);
PARSABLE_RESOURCE_MAP.set('CommunicationRequest', CommunicationRequest);
PARSABLE_RESOURCE_MAP.set('CompartmentDefinition', CompartmentDefinition);
PARSABLE_RESOURCE_MAP.set('Composition', Composition);
PARSABLE_RESOURCE_MAP.set('ConceptMap', ConceptMap);
PARSABLE_RESOURCE_MAP.set('Condition', Condition);
PARSABLE_RESOURCE_MAP.set('Consent', Consent);
PARSABLE_RESOURCE_MAP.set('Contract', Contract);
PARSABLE_RESOURCE_MAP.set('Coverage', Coverage);
PARSABLE_RESOURCE_MAP.set('CoverageEligibilityRequest', CoverageEligibilityRequest);
PARSABLE_RESOURCE_MAP.set('CoverageEligibilityResponse', CoverageEligibilityResponse);
PARSABLE_RESOURCE_MAP.set('DetectedIssue', DetectedIssue);
PARSABLE_RESOURCE_MAP.set('Device', Device);
PARSABLE_RESOURCE_MAP.set('DeviceDefinition', DeviceDefinition);
PARSABLE_RESOURCE_MAP.set('DeviceMetric', DeviceMetric);
PARSABLE_RESOURCE_MAP.set('DeviceRequest', DeviceRequest);
PARSABLE_RESOURCE_MAP.set('DeviceUseStatement', DeviceUseStatement);
PARSABLE_RESOURCE_MAP.set('DiagnosticReport', DiagnosticReport);
PARSABLE_RESOURCE_MAP.set('DocumentManifest', DocumentManifest);
PARSABLE_RESOURCE_MAP.set('DocumentReference', DocumentReference);
PARSABLE_RESOURCE_MAP.set('EffectEvidenceSynthesis', EffectEvidenceSynthesis);
PARSABLE_RESOURCE_MAP.set('Encounter', Encounter);
PARSABLE_RESOURCE_MAP.set('Endpoint', Endpoint);
PARSABLE_RESOURCE_MAP.set('EnrollmentRequest', EnrollmentRequest);
PARSABLE_RESOURCE_MAP.set('EnrollmentResponse', EnrollmentResponse);
PARSABLE_RESOURCE_MAP.set('EpisodeOfCare', EpisodeOfCare);
PARSABLE_RESOURCE_MAP.set('EventDefinition', EventDefinition);
PARSABLE_RESOURCE_MAP.set('Evidence', Evidence);
PARSABLE_RESOURCE_MAP.set('EvidenceVariable', EvidenceVariable);
PARSABLE_RESOURCE_MAP.set('ExampleScenario', ExampleScenario);
PARSABLE_RESOURCE_MAP.set('ExplanationOfBenefit', ExplanationOfBenefit);
PARSABLE_RESOURCE_MAP.set('FamilyMemberHistory', FamilyMemberHistory);
PARSABLE_RESOURCE_MAP.set('Flag', Flag);
PARSABLE_RESOURCE_MAP.set('Goal', Goal);
PARSABLE_RESOURCE_MAP.set('GraphDefinition', GraphDefinition);
PARSABLE_RESOURCE_MAP.set('Group', Group);
PARSABLE_RESOURCE_MAP.set('GuidanceResponse', GuidanceResponse);
PARSABLE_RESOURCE_MAP.set('HealthcareService', HealthcareService);
PARSABLE_RESOURCE_MAP.set('ImagingStudy', ImagingStudy);
PARSABLE_RESOURCE_MAP.set('Immunization', Immunization);
PARSABLE_RESOURCE_MAP.set('ImmunizationEvaluation', ImmunizationEvaluation);
PARSABLE_RESOURCE_MAP.set('ImmunizationRecommendation', ImmunizationRecommendation);
PARSABLE_RESOURCE_MAP.set('ImplementationGuide', ImplementationGuide);
PARSABLE_RESOURCE_MAP.set('InsurancePlan', InsurancePlan);
PARSABLE_RESOURCE_MAP.set('Invoice', Invoice);
PARSABLE_RESOURCE_MAP.set('Library', Library);
PARSABLE_RESOURCE_MAP.set('Linkage', Linkage);
PARSABLE_RESOURCE_MAP.set('List', List);
PARSABLE_RESOURCE_MAP.set('Location', Location);
PARSABLE_RESOURCE_MAP.set('Measure', Measure);
PARSABLE_RESOURCE_MAP.set('MeasureReport', MeasureReport);
PARSABLE_RESOURCE_MAP.set('Media', Media);
PARSABLE_RESOURCE_MAP.set('Medication', Medication);
PARSABLE_RESOURCE_MAP.set('MedicationAdministration', MedicationAdministration);
PARSABLE_RESOURCE_MAP.set('MedicationDispense', MedicationDispense);
PARSABLE_RESOURCE_MAP.set('MedicationKnowledge', MedicationKnowledge);
PARSABLE_RESOURCE_MAP.set('MedicationRequest', MedicationRequest);
PARSABLE_RESOURCE_MAP.set('MedicationStatement', MedicationStatement);
PARSABLE_RESOURCE_MAP.set('MedicinalProduct', MedicinalProduct);
PARSABLE_RESOURCE_MAP.set('MedicinalProductAuthorization', MedicinalProductAuthorization);
PARSABLE_RESOURCE_MAP.set('MedicinalProductContraindication', MedicinalProductContraindication);
PARSABLE_RESOURCE_MAP.set('MedicinalProductIndication', MedicinalProductIndication);
PARSABLE_RESOURCE_MAP.set('MedicinalProductIngredient', MedicinalProductIngredient);
PARSABLE_RESOURCE_MAP.set('MedicinalProductInteraction', MedicinalProductInteraction);
PARSABLE_RESOURCE_MAP.set('MedicinalProductManufactured', MedicinalProductManufactured);
PARSABLE_RESOURCE_MAP.set('MedicinalProductPackaged', MedicinalProductPackaged);
PARSABLE_RESOURCE_MAP.set('MedicinalProductPharmaceutical', MedicinalProductPharmaceutical);
PARSABLE_RESOURCE_MAP.set('MedicinalProductUndesirableEffect', MedicinalProductUndesirableEffect);
PARSABLE_RESOURCE_MAP.set('MessageDefinition', MessageDefinition);
PARSABLE_RESOURCE_MAP.set('MessageHeader', MessageHeader);
PARSABLE_RESOURCE_MAP.set('MolecularSequence', MolecularSequence);
PARSABLE_RESOURCE_MAP.set('NamingSystem', NamingSystem);
PARSABLE_RESOURCE_MAP.set('NutritionOrder', NutritionOrder);
PARSABLE_RESOURCE_MAP.set('Observation', Observation);
PARSABLE_RESOURCE_MAP.set('ObservationDefinition', ObservationDefinition);
PARSABLE_RESOURCE_MAP.set('OperationDefinition', OperationDefinition);
PARSABLE_RESOURCE_MAP.set('OperationOutcome', OperationOutcome);
PARSABLE_RESOURCE_MAP.set('Organization', Organization);
PARSABLE_RESOURCE_MAP.set('OrganizationAffiliation', OrganizationAffiliation);
PARSABLE_RESOURCE_MAP.set('Parameters', Parameters);
PARSABLE_RESOURCE_MAP.set('Patient', Patient);
PARSABLE_RESOURCE_MAP.set('PaymentNotice', PaymentNotice);
PARSABLE_RESOURCE_MAP.set('PaymentReconciliation', PaymentReconciliation);
PARSABLE_RESOURCE_MAP.set('Person', Person);
PARSABLE_RESOURCE_MAP.set('PlanDefinition', PlanDefinition);
PARSABLE_RESOURCE_MAP.set('Practitioner', Practitioner);
PARSABLE_RESOURCE_MAP.set('PractitionerRole', PractitionerRole);
PARSABLE_RESOURCE_MAP.set('Procedure', Procedure);
PARSABLE_RESOURCE_MAP.set('Provenance', Provenance);
PARSABLE_RESOURCE_MAP.set('Questionnaire', Questionnaire);
PARSABLE_RESOURCE_MAP.set('QuestionnaireResponse', QuestionnaireResponse);
PARSABLE_RESOURCE_MAP.set('RelatedPerson', RelatedPerson);
PARSABLE_RESOURCE_MAP.set('RequestGroup', RequestGroup);
PARSABLE_RESOURCE_MAP.set('ResearchDefinition', ResearchDefinition);
PARSABLE_RESOURCE_MAP.set('ResearchElementDefinition', ResearchElementDefinition);
PARSABLE_RESOURCE_MAP.set('ResearchStudy', ResearchStudy);
PARSABLE_RESOURCE_MAP.set('ResearchSubject', ResearchSubject);
PARSABLE_RESOURCE_MAP.set('RiskAssessment', RiskAssessment);
PARSABLE_RESOURCE_MAP.set('RiskEvidenceSynthesis', RiskEvidenceSynthesis);
PARSABLE_RESOURCE_MAP.set('Schedule', Schedule);
PARSABLE_RESOURCE_MAP.set('SearchParameter', SearchParameter);
PARSABLE_RESOURCE_MAP.set('ServiceRequest', ServiceRequest);
PARSABLE_RESOURCE_MAP.set('Slot', Slot);
PARSABLE_RESOURCE_MAP.set('Specimen', Specimen);
PARSABLE_RESOURCE_MAP.set('SpecimenDefinition', SpecimenDefinition);
PARSABLE_RESOURCE_MAP.set('StructureDefinition', StructureDefinition);
PARSABLE_RESOURCE_MAP.set('StructureMap', StructureMap);
PARSABLE_RESOURCE_MAP.set('Subscription', Subscription);
PARSABLE_RESOURCE_MAP.set('Substance', Substance);
PARSABLE_RESOURCE_MAP.set('SubstanceNucleicAcid', SubstanceNucleicAcid);
PARSABLE_RESOURCE_MAP.set('SubstancePolymer', SubstancePolymer);
PARSABLE_RESOURCE_MAP.set('SubstanceProtein', SubstanceProtein);
PARSABLE_RESOURCE_MAP.set('SubstanceReferenceInformation', SubstanceReferenceInformation);
PARSABLE_RESOURCE_MAP.set('SubstanceSourceMaterial', SubstanceSourceMaterial);
PARSABLE_RESOURCE_MAP.set('SubstanceSpecification', SubstanceSpecification);
PARSABLE_RESOURCE_MAP.set('SupplyDelivery', SupplyDelivery);
PARSABLE_RESOURCE_MAP.set('SupplyRequest', SupplyRequest);
PARSABLE_RESOURCE_MAP.set('Task', Task);
PARSABLE_RESOURCE_MAP.set('TerminologyCapabilities', TerminologyCapabilities);
PARSABLE_RESOURCE_MAP.set('TestReport', TestReport);
PARSABLE_RESOURCE_MAP.set('TestScript', TestScript);
PARSABLE_RESOURCE_MAP.set('ValueSet', ValueSet);
PARSABLE_RESOURCE_MAP.set('VerificationResult', VerificationResult);
PARSABLE_RESOURCE_MAP.set('VisionPrescription', VisionPrescription);
