/*
 * Copyright (c) 2025. Joe Paquette
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

import { BasePackageLoader, LoadStatus, SafeMode } from 'fhir-package-loader';
import {
  FhirPackage,
  generatorPackageLoader,
  GeneratorPackageLoaderOptions,
} from '../../generator-lib/ts-datamodel-generator-helpers';
import { HbsStructureDefinition } from '../../generator-lib/templates/utils-hbs';

/**
 * Returns the generatorPackageLoader() implementation of the BasePackageLoader using SafeMode.CLONE
 * for testing purposes
 *
 * @param fhirPackage - FHIR package definition
 * @returns Promise<BasePackageLoader>
 */
export async function getGeneratorPackageLoader(fhirPackage: FhirPackage): Promise<BasePackageLoader> {
  const fplLogger = (level: string, message: string) => {
    console.log(`${level}: ${message}`);
  };
  const options: GeneratorPackageLoaderOptions = {
    log: fplLogger,
    safeMode: SafeMode.CLONE,
    cacheRootPath: fhirPackage.pkgLoaderCacheRootPath,
  };
  const packageLoader: BasePackageLoader = await generatorPackageLoader(options);
  const status = await packageLoader.loadPackage(fhirPackage.pkgName, fhirPackage.pkgVersion);
  if (status !== LoadStatus.LOADED) {
    throw new Error(
      `Failed to load FHIR package ${fhirPackage.pkgName}@${fhirPackage.pkgVersion}; (actual load status: ${status})`,
    );
  }

  return packageLoader;
}

// HbsStructureDefinition for AuditEvent resource used to provide inputs to various unit tests
export const testAuditEventSdHbs = {
  url: 'http://hl7.org/fhir/StructureDefinition/AuditEvent',
  name: 'AuditEvent',
  type: 'AuditEvent',
  kind: 'resource',
  baseDefinitionType: 'DomainResource',
  description:
    'A record of an event made for purposes of maintaining a security log. Typical uses include detection of intrusion attempts and monitoring for inappropriate usage.',
  fhirVersion: '4.0.1',
  parentComponent: {
    parentUrl: 'http://hl7.org/fhir/StructureDefinition/AuditEvent',
    parentName: 'AuditEvent',
    parentType: 'AuditEvent',
    parentKind: 'resource',
    parentFieldName: 'AuditEvent',
    componentName: 'AuditEvent',
    baseDefinitionType: 'DomainResource',
    isComponentResource: false,
    isComponentDomainResource: true,
    isComponentBackboneElement: false,
    isComponentBackboneType: false,
    isComponentDataType: false,
    isComponentElement: false,
    hasParsableDataType: true,
    rootElement: {
      short: 'Event record kept for security purposes',
      definition:
        'A record of an event made for purposes of maintaining a security log. Typical uses include detection of intrusion attempts and monitoring for inappropriate usage.',
      comment: 'Based on IHE-ATNA.',
    },
    numRequiredFields: 4,
    hasRequiredFields: true,
    hasResourceFields: false,
    hasPrimitiveFields: true,
    hasOnlyOnePrimitiveField: false,
    hasChoiceFields: false,
    hasCodeSystemEnums: false,
    requiredConstructor: true,
    elementDefinitions: [
      {
        path: 'AuditEvent.type',
        fieldName: 'type',
        fieldIdentifierName: 'type_',
        short: 'Type/identifier of event',
        definition:
          'Identifier for a family of the event.  For example, a menu item, program, rule, policy, function code, application name or URL. It identifies the performed function.',
        requirements:
          'This identifies the performed function. For "Execute" Event Action Code audit records, this identifies the application function performed.',
        min: 1,
        max: '1',
        cardinality: '1..1',
        isRequired: true,
        isArray: false,
        isOptionalItem: false,
        isOptionalList: false,
        isRequiredItem: true,
        isRequiredList: false,
        type: {
          fhirDataType: 'Coding',
          code: 'Coding',
        },
        isBackboneType: false,
        isChoiceType: false,
        isComplexType: true,
        isEnumCodeType: false,
        isPrimitiveType: false,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: true,
      },
      {
        path: 'AuditEvent.subtype',
        fieldName: 'subtype',
        fieldIdentifierName: 'subtype',
        short: 'More specific type/id for the event',
        definition: 'Identifier for the category of event.',
        requirements: 'This field enables queries of messages by implementation-defined event categories.',
        min: 0,
        max: '*',
        cardinality: '0..*',
        isRequired: false,
        isArray: true,
        isOptionalItem: false,
        isOptionalList: true,
        isRequiredItem: false,
        isRequiredList: false,
        type: {
          fhirDataType: 'Coding',
          code: 'Coding',
        },
        isBackboneType: false,
        isChoiceType: false,
        isComplexType: true,
        isEnumCodeType: false,
        isPrimitiveType: false,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: true,
      },
      {
        path: 'AuditEvent.action',
        fieldName: 'action',
        fieldIdentifierName: 'action',
        short: 'Type of action performed during the event',
        definition: 'Indicator for type of action performed during the event that generated the audit.',
        requirements:
          'This broadly indicates what kind of action was done on the AuditEvent.entity by the AuditEvent.agent.',
        min: 0,
        max: '1',
        cardinality: '0..1',
        isRequired: false,
        isArray: false,
        isOptionalItem: true,
        isOptionalList: false,
        isRequiredItem: false,
        isRequiredList: false,
        type: {
          fhirDataType: 'code',
          code: 'CodeType',
          primitiveJsonType: 'string',
        },
        isBackboneType: false,
        isChoiceType: false,
        isComplexType: false,
        isEnumCodeType: false,
        isPrimitiveType: true,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: true,
      },
      {
        path: 'AuditEvent.period',
        fieldName: 'period',
        fieldIdentifierName: 'period',
        short: 'When the activity occurred',
        definition: 'The period during which the activity occurred.',
        comment:
          'The period can be a little arbitrary; where possible, the time should correspond to human assessment of the activity time.',
        min: 0,
        max: '1',
        cardinality: '0..1',
        isRequired: false,
        isArray: false,
        isOptionalItem: true,
        isOptionalList: false,
        isRequiredItem: false,
        isRequiredList: false,
        type: {
          fhirDataType: 'Period',
          code: 'Period',
        },
        isBackboneType: false,
        isChoiceType: false,
        isComplexType: true,
        isEnumCodeType: false,
        isPrimitiveType: false,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: false,
      },
      {
        path: 'AuditEvent.recorded',
        fieldName: 'recorded',
        fieldIdentifierName: 'recorded',
        short: 'Time when the event was recorded',
        definition: 'The time when the event was recorded.',
        comment:
          'In a distributed system, some sort of common time base (e.g. an NTP [RFC1305] server) is a good implementation tactic.',
        requirements:
          'This ties an event to a specific date and time. Security audits typically require a consistent time base (e.g. UTC), to eliminate time-zone issues arising from geographical distribution.',
        min: 1,
        max: '1',
        cardinality: '1..1',
        isRequired: true,
        isArray: false,
        isOptionalItem: false,
        isOptionalList: false,
        isRequiredItem: true,
        isRequiredList: false,
        type: {
          fhirDataType: 'instant',
          code: 'InstantType',
          primitiveJsonType: 'string',
        },
        isBackboneType: false,
        isChoiceType: false,
        isComplexType: false,
        isEnumCodeType: false,
        isPrimitiveType: true,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: true,
      },
      {
        path: 'AuditEvent.outcome',
        fieldName: 'outcome',
        fieldIdentifierName: 'outcome',
        short: 'Whether the event succeeded or failed',
        definition: 'Indicates whether the event succeeded or failed.',
        comment:
          'In some cases a "success" may be partial, for example, an incomplete or interrupted transfer of a radiological study. For the purpose of establishing accountability, these distinctions are not relevant.',
        min: 0,
        max: '1',
        cardinality: '0..1',
        isRequired: false,
        isArray: false,
        isOptionalItem: true,
        isOptionalList: false,
        isRequiredItem: false,
        isRequiredList: false,
        type: {
          fhirDataType: 'code',
          code: 'CodeType',
          primitiveJsonType: 'string',
        },
        isBackboneType: false,
        isChoiceType: false,
        isComplexType: false,
        isEnumCodeType: false,
        isPrimitiveType: true,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: true,
      },
      {
        path: 'AuditEvent.outcomeDesc',
        fieldName: 'outcomeDesc',
        fieldIdentifierName: 'outcomeDesc',
        short: 'Description of the event outcome',
        definition: 'A free text description of the outcome of the event.',
        min: 0,
        max: '1',
        cardinality: '0..1',
        isRequired: false,
        isArray: false,
        isOptionalItem: true,
        isOptionalList: false,
        isRequiredItem: false,
        isRequiredList: false,
        type: {
          fhirDataType: 'string',
          code: 'StringType',
          primitiveJsonType: 'string',
        },
        isBackboneType: false,
        isChoiceType: false,
        isComplexType: false,
        isEnumCodeType: false,
        isPrimitiveType: true,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: true,
      },
      {
        path: 'AuditEvent.purposeOfEvent',
        fieldName: 'purposeOfEvent',
        fieldIdentifierName: 'purposeOfEvent',
        short: 'The purposeOfUse of the event',
        definition: 'The purposeOfUse (reason) that was used during the event being recorded.',
        comment:
          'Use AuditEvent.agent.purposeOfUse when you know that it is specific to the agent, otherwise use AuditEvent.purposeOfEvent. For example, during a machine-to-machine transfer it might not be obvious to the audit system who caused the event, but it does know why.',
        min: 0,
        max: '*',
        cardinality: '0..*',
        isRequired: false,
        isArray: true,
        isOptionalItem: false,
        isOptionalList: true,
        isRequiredItem: false,
        isRequiredList: false,
        type: {
          fhirDataType: 'CodeableConcept',
          code: 'CodeableConcept',
        },
        isBackboneType: false,
        isChoiceType: false,
        isComplexType: true,
        isEnumCodeType: false,
        isPrimitiveType: false,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: true,
      },
      {
        path: 'AuditEvent.agent',
        fieldName: 'agent',
        fieldIdentifierName: 'agent',
        short: 'Actor involved in the event',
        definition: 'An actor taking an active role in the event or activity that is logged.',
        comment:
          'Several agents may be associated (i.e. have some responsibility for an activity) with an event or activity. For example, an activity may be initiated by one user for other users or involve more than one user. However, only one user may be the initiator/requestor for the activity.',
        requirements:
          'An agent can be a person, an organization, software, device, or other actors that may be ascribed responsibility.',
        min: 1,
        max: '*',
        cardinality: '1..*',
        isRequired: true,
        isArray: true,
        isOptionalItem: false,
        isOptionalList: false,
        isRequiredItem: false,
        isRequiredList: true,
        type: {
          fhirDataType: 'BackboneElement',
          code: 'AuditEventAgentComponent',
        },
        isBackboneType: true,
        isChoiceType: false,
        isComplexType: false,
        isEnumCodeType: false,
        isPrimitiveType: false,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: false,
      },
      {
        path: 'AuditEvent.source',
        fieldName: 'source',
        fieldIdentifierName: 'source',
        short: 'Audit Event Reporter',
        definition: 'The system that is reporting the event.',
        comment:
          'Since multi-tier, distributed, or composite applications make source identification ambiguous, this collection of fields may repeat for each application or process actively involved in the event. For example, multiple value-sets can identify participating web servers, application processes, and database server threads in an n-tier distributed application. Passive event participants (e.g. low-level network transports) need not be identified.',
        requirements: 'The event is reported by one source.',
        min: 1,
        max: '1',
        cardinality: '1..1',
        isRequired: true,
        isArray: false,
        isOptionalItem: false,
        isOptionalList: false,
        isRequiredItem: true,
        isRequiredList: false,
        type: {
          fhirDataType: 'BackboneElement',
          code: 'AuditEventSourceComponent',
        },
        isBackboneType: true,
        isChoiceType: false,
        isComplexType: false,
        isEnumCodeType: false,
        isPrimitiveType: false,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: false,
      },
      {
        path: 'AuditEvent.entity',
        fieldName: 'entity',
        fieldIdentifierName: 'entity',
        short: 'Data or objects used',
        definition: 'Specific instances of data or objects that have been accessed.',
        comment:
          'Required unless the values for event identification, agent identification, and audit source identification are sufficient to document the entire auditable event. Because events may have more than one entity, this group can be a repeating set of values.',
        requirements: 'The event may have other entities involved.',
        min: 0,
        max: '*',
        cardinality: '0..*',
        isRequired: false,
        isArray: true,
        isOptionalItem: false,
        isOptionalList: true,
        isRequiredItem: false,
        isRequiredList: false,
        type: {
          fhirDataType: 'BackboneElement',
          code: 'AuditEventEntityComponent',
        },
        isBackboneType: true,
        isChoiceType: false,
        isComplexType: false,
        isEnumCodeType: false,
        isPrimitiveType: false,
        isReferenceType: false,
        isResourceType: false,
        isModifier: false,
        isSummary: false,
      },
    ],
    fhirCoreImports: [
      'CodeType',
      'FhirDataTypeParser',
      'FhirError',
      'IBase',
      'INSTANCE_EMPTY_ERROR_MSG',
      'InstantType',
      'JSON',
      'PrimitiveType',
      'REQUIRED_PROPERTIES_DO_NOT_EXIST',
      'REQUIRED_PROPERTIES_REQD_IN_JSON',
      'StringType',
      'assertFhirType',
      'assertFhirTypeList',
      'assertIsDefined',
      'assertIsDefinedList',
      'copyListValues',
      'fhirCode',
      'fhirCodeSchema',
      'fhirInstant',
      'fhirInstantSchema',
      'fhirString',
      'fhirStringSchema',
      'getPrimitiveTypeJson',
      'isDefined',
      'isDefinedList',
      'isElementEmpty',
      'isEmpty',
      'parseCodeType',
      'parseFhirPrimitiveData',
      'parseInstantType',
      'parseStringType',
      'setFhirBackboneElementJson',
      'setFhirBackboneElementListJson',
      'setFhirComplexJson',
      'setFhirComplexListJson',
      'setFhirPrimitiveJson',
    ],
    generatedImports: [
      'CodeableConcept',
      'Coding',
      'DomainResource',
      'FhirResourceParser',
      'FhirResourceType',
      'PARSABLE_DATATYPE_MAP',
      'Period',
    ],
  },
  hasChildComponents: true,
  childComponents: [
    {
      parentUrl: 'http://hl7.org/fhir/StructureDefinition/AuditEvent',
      parentName: 'AuditEvent',
      parentType: 'AuditEvent',
      parentKind: 'resource',
      parentFieldName: 'AuditEvent.agent',
      componentName: 'AuditEventAgentComponent',
      baseDefinitionType: 'BackboneElement',
      isComponentResource: false,
      isComponentDomainResource: false,
      isComponentBackboneElement: true,
      isComponentBackboneType: false,
      isComponentDataType: false,
      isComponentElement: false,
      hasParsableDataType: true,
      rootElement: {
        path: 'AuditEvent.agent',
        componentName: 'AuditEventAgentComponent',
        componentLevel: 2,
        short: 'Actor involved in the event',
        definition: 'An actor taking an active role in the event or activity that is logged.',
        comment:
          'Several agents may be associated (i.e. have some responsibility for an activity) with an event or activity. For example, an activity may be initiated by one user for other users or involve more than one user. However, only one user may be the initiator/requestor for the activity.',
        requirements:
          'An agent can be a person, an organization, software, device, or other actors that may be ascribed responsibility.',
        typeCode: 'BackboneElement',
      },
      numRequiredFields: 1,
      hasRequiredFields: true,
      hasResourceFields: false,
      hasPrimitiveFields: true,
      hasOnlyOnePrimitiveField: false,
      hasChoiceFields: false,
      hasCodeSystemEnums: false,
      requiredConstructor: true,
      elementDefinitions: [
        {
          path: 'AuditEvent.agent.type',
          fieldName: 'type',
          fieldIdentifierName: 'type_',
          short: 'How agent participated',
          definition: 'Specification of the participation type the user plays when performing the event.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'CodeableConcept',
            code: 'CodeableConcept',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: true,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.agent.role',
          fieldName: 'role',
          fieldIdentifierName: 'role',
          short: 'Agent role in the event',
          definition:
            'The security role that the user was acting under, that come from local codes defined by the access control security system (e.g. RBAC, ABAC) used in the local context.',
          comment: 'Should be roles relevant to the event. Should  not be an exhaustive list of roles.',
          requirements:
            "This value ties an audited event to a user\\'s role(s). It is an optional value that might be used to group events for analysis by user functional role categories.",
          min: 0,
          max: '*',
          cardinality: '0..*',
          isRequired: false,
          isArray: true,
          isOptionalItem: false,
          isOptionalList: true,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'CodeableConcept',
            code: 'CodeableConcept',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: true,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.agent.who',
          fieldName: 'who',
          fieldIdentifierName: 'who',
          short: 'Identifier of who',
          definition: 'Reference to who this agent is that was involved in the event.',
          comment: 'Where a User ID is available it will go into who.identifier.',
          requirements: 'This field ties an audit event to a specific resource or identifier.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'Reference',
            code: 'Reference',
            targetProfile: [
              'http://hl7.org/fhir/StructureDefinition/PractitionerRole',
              'http://hl7.org/fhir/StructureDefinition/Practitioner',
              'http://hl7.org/fhir/StructureDefinition/Organization',
              'http://hl7.org/fhir/StructureDefinition/Device',
              'http://hl7.org/fhir/StructureDefinition/Patient',
              'http://hl7.org/fhir/StructureDefinition/RelatedPerson',
            ],
            targetResource: ['PractitionerRole', 'Practitioner', 'Organization', 'Device', 'Patient', 'RelatedPerson'],
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: true,
          isResourceType: false,
          isModifier: false,
          isSummary: true,
        },
        {
          path: 'AuditEvent.agent.altId',
          fieldName: 'altId',
          fieldIdentifierName: 'altId',
          short: 'Alternative User identity',
          definition:
            'Alternative agent Identifier. For a human, this should be a user identifier text string from authentication system. This identifier would be one known to a common authentication system (e.g. single sign-on), if available.',
          requirements:
            'In some situations, a human user may authenticate with one identity but, to access a specific application system, may use a synonymous identify. For example, some "single sign on" implementations will do this. The alternative identifier would then be the original identify  used for authentication, and the User ID is the one known to and used by the application.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'string',
            code: 'StringType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.agent.name',
          fieldName: 'name',
          fieldIdentifierName: 'name',
          short: 'Human friendly name for the agent',
          definition: 'Human-meaningful name for the agent.',
          requirements:
            'The User ID and Authorization User ID may be internal or otherwise obscure values. This field assists the auditor in identifying the actual user.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'string',
            code: 'StringType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.agent.requestor',
          fieldName: 'requestor',
          fieldIdentifierName: 'requestor',
          short: 'Whether user is initiator',
          definition: 'Indicator that the user is or is not the requestor, or initiator, for the event being audited.',
          comment:
            'There can only be one initiator. If the initiator is not clear, then do not choose any one agent as the initiator.',
          requirements:
            'This value is used to distinguish between requestor-users and recipient-users. For example, one person may initiate a report-output to be sent to another user.',
          min: 1,
          max: '1',
          cardinality: '1..1',
          isRequired: true,
          isArray: false,
          isOptionalItem: false,
          isOptionalList: false,
          isRequiredItem: true,
          isRequiredList: false,
          type: {
            fhirDataType: 'boolean',
            code: 'BooleanType',
            primitiveJsonType: 'boolean',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: true,
        },
        {
          path: 'AuditEvent.agent.location',
          fieldName: 'location',
          fieldIdentifierName: 'location',
          short: 'Where',
          definition: 'Where the event occurred.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'Reference',
            code: 'Reference',
            targetProfile: ['http://hl7.org/fhir/StructureDefinition/Location'],
            targetResource: ['Location'],
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: true,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.agent.policy',
          fieldName: 'policy',
          fieldIdentifierName: 'policy',
          short: 'Policy that authorized event',
          definition:
            'The policy or plan that authorized the activity being recorded. Typically, a single activity may have multiple applicable policies, such as patient consent, guarantor funding, etc. The policy would also indicate the security token used.',
          comment:
            'For example: Where an OAuth token authorizes, the unique identifier from the OAuth token is placed into the policy element Where a policy engine (e.g. XACML) holds policy logic, the unique policy identifier is placed into the policy element.',
          requirements: 'This value is used retrospectively to determine the authorization policies.',
          min: 0,
          max: '*',
          cardinality: '0..*',
          isRequired: false,
          isArray: true,
          isOptionalItem: false,
          isOptionalList: true,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'uri',
            code: 'UriType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.agent.media',
          fieldName: 'media',
          fieldIdentifierName: 'media',
          short: 'Type of media',
          definition: 'Type of media involved. Used when the event is about exporting/importing onto media.',
          requirements:
            'Usually, this is used instead of specifying a network address. This field is not used for Media Id (i.e. the serial number of a CD).',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'Coding',
            code: 'Coding',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: true,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.agent.network',
          fieldName: 'network',
          fieldIdentifierName: 'network',
          short: 'Logical network location for application activity',
          definition: 'Logical network location for application activity, if the activity has a network location.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'BackboneElement',
            code: 'AuditEventAgentNetworkComponent',
          },
          isBackboneType: true,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.agent.purposeOfUse',
          fieldName: 'purposeOfUse',
          fieldIdentifierName: 'purposeOfUse',
          short: 'Reason given for this user',
          definition:
            'The reason (purpose of use), specific to this agent, that was used during the event being recorded.',
          comment:
            'Use AuditEvent.agent.purposeOfUse when you know that is specific to the agent, otherwise use AuditEvent.purposeOfEvent. For example, during a machine-to-machine transfer it might not be obvious to the audit system who caused the event, but it does know why.',
          min: 0,
          max: '*',
          cardinality: '0..*',
          isRequired: false,
          isArray: true,
          isOptionalItem: false,
          isOptionalList: true,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'CodeableConcept',
            code: 'CodeableConcept',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: true,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
      ],
      fhirCoreImports: [
        'BackboneElement',
        'BooleanType',
        'FhirDataTypeParser',
        'FhirError',
        'IBase',
        'INSTANCE_EMPTY_ERROR_MSG',
        'JSON',
        'PrimitiveType',
        'PrimitiveTypeJson',
        'REQUIRED_PROPERTIES_DO_NOT_EXIST',
        'REQUIRED_PROPERTIES_REQD_IN_JSON',
        'StringType',
        'UriType',
        'assertFhirType',
        'assertFhirTypeList',
        'assertIsDefined',
        'copyListValues',
        'fhirBoolean',
        'fhirBooleanSchema',
        'fhirString',
        'fhirStringSchema',
        'fhirUri',
        'fhirUriSchema',
        'getPrimitiveTypeJson',
        'getPrimitiveTypeListJson',
        'isDefined',
        'isDefinedList',
        'isElementEmpty',
        'isEmpty',
        'parseBooleanType',
        'parseFhirPrimitiveData',
        'parseStringType',
        'parseUriType',
        'setFhirBackboneElementJson',
        'setFhirComplexJson',
        'setFhirComplexListJson',
        'setFhirPrimitiveJson',
        'setFhirPrimitiveListJson',
      ],
      generatedImports: ['CodeableConcept', 'Coding', 'PARSABLE_DATATYPE_MAP', 'Reference', 'ReferenceTargets'],
    },
    {
      parentUrl: 'http://hl7.org/fhir/StructureDefinition/AuditEvent',
      parentName: 'AuditEvent',
      parentType: 'AuditEvent',
      parentKind: 'resource',
      parentFieldName: 'AuditEvent.agent.network',
      componentName: 'AuditEventAgentNetworkComponent',
      baseDefinitionType: 'BackboneElement',
      isComponentResource: false,
      isComponentDomainResource: false,
      isComponentBackboneElement: true,
      isComponentBackboneType: false,
      isComponentDataType: false,
      isComponentElement: false,
      hasParsableDataType: true,
      rootElement: {
        path: 'AuditEvent.agent.network',
        componentName: 'AuditEventAgentNetworkComponent',
        componentLevel: 3,
        short: 'Logical network location for application activity',
        definition: 'Logical network location for application activity, if the activity has a network location.',
        typeCode: 'BackboneElement',
      },
      numRequiredFields: 0,
      hasRequiredFields: false,
      hasResourceFields: false,
      hasPrimitiveFields: true,
      hasOnlyOnePrimitiveField: false,
      hasChoiceFields: false,
      hasCodeSystemEnums: false,
      requiredConstructor: false,
      elementDefinitions: [
        {
          path: 'AuditEvent.agent.network.address',
          fieldName: 'address',
          fieldIdentifierName: 'address',
          short: 'Identifier for the network access point of the user device',
          definition: 'An identifier for the network access point of the user device for the audit event.',
          comment: 'This could be a device id, IP address or some other identifier associated with a device.',
          requirements:
            "This datum identifies the user\\'s network access point, which may be distinct from the server that performed the action. It is an optional value that may be used to group events recorded on separate servers for analysis of a specific network access point\\'s data access across all servers.",
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'string',
            code: 'StringType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.agent.network.type',
          fieldName: 'type',
          fieldIdentifierName: 'type_',
          short: 'The type of network access point',
          definition: 'An identifier for the type of network access point that originated the audit event.',
          requirements:
            "This datum identifies the type of network access point identifier of the user device for the audit event. It is an optional value that may be used to group events recorded on separate servers for analysis of access according to a network access point\\'s type.",
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'code',
            code: 'CodeType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
      ],
      fhirCoreImports: [
        'BackboneElement',
        'CodeType',
        'FhirDataTypeParser',
        'IBase',
        'INSTANCE_EMPTY_ERROR_MSG',
        'JSON',
        'StringType',
        'assertFhirType',
        'fhirCode',
        'fhirCodeSchema',
        'fhirString',
        'fhirStringSchema',
        'getPrimitiveTypeJson',
        'isDefined',
        'isElementEmpty',
        'isEmpty',
        'parseCodeType',
        'parseFhirPrimitiveData',
        'parseStringType',
        'setFhirPrimitiveJson',
      ],
      generatedImports: ['PARSABLE_DATATYPE_MAP'],
    },
    {
      parentUrl: 'http://hl7.org/fhir/StructureDefinition/AuditEvent',
      parentName: 'AuditEvent',
      parentType: 'AuditEvent',
      parentKind: 'resource',
      parentFieldName: 'AuditEvent.source',
      componentName: 'AuditEventSourceComponent',
      baseDefinitionType: 'BackboneElement',
      isComponentResource: false,
      isComponentDomainResource: false,
      isComponentBackboneElement: true,
      isComponentBackboneType: false,
      isComponentDataType: false,
      isComponentElement: false,
      hasParsableDataType: true,
      rootElement: {
        path: 'AuditEvent.source',
        componentName: 'AuditEventSourceComponent',
        componentLevel: 2,
        short: 'Audit Event Reporter',
        definition: 'The system that is reporting the event.',
        comment:
          'Since multi-tier, distributed, or composite applications make source identification ambiguous, this collection of fields may repeat for each application or process actively involved in the event. For example, multiple value-sets can identify participating web servers, application processes, and database server threads in an n-tier distributed application. Passive event participants (e.g. low-level network transports) need not be identified.',
        requirements: 'The event is reported by one source.',
        typeCode: 'BackboneElement',
      },
      numRequiredFields: 1,
      hasRequiredFields: true,
      hasResourceFields: false,
      hasPrimitiveFields: true,
      hasOnlyOnePrimitiveField: true,
      hasChoiceFields: false,
      hasCodeSystemEnums: false,
      requiredConstructor: true,
      elementDefinitions: [
        {
          path: 'AuditEvent.source.site',
          fieldName: 'site',
          fieldIdentifierName: 'site',
          short: 'Logical source location within the enterprise',
          definition:
            'Logical source location within the healthcare enterprise network.  For example, a hospital or other provider location within a multi-entity provider group.',
          requirements:
            'This value differentiates among the sites in a multi-site enterprise health information system.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'string',
            code: 'StringType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.source.observer',
          fieldName: 'observer',
          fieldIdentifierName: 'observer',
          short: 'The identity of source detecting the event',
          definition: 'Identifier of the source where the event was detected.',
          requirements:
            'This field ties the event to a specific source system. It may be used to group events for analysis according to where the event was detected.',
          min: 1,
          max: '1',
          cardinality: '1..1',
          isRequired: true,
          isArray: false,
          isOptionalItem: false,
          isOptionalList: false,
          isRequiredItem: true,
          isRequiredList: false,
          type: {
            fhirDataType: 'Reference',
            code: 'Reference',
            targetProfile: [
              'http://hl7.org/fhir/StructureDefinition/PractitionerRole',
              'http://hl7.org/fhir/StructureDefinition/Practitioner',
              'http://hl7.org/fhir/StructureDefinition/Organization',
              'http://hl7.org/fhir/StructureDefinition/Device',
              'http://hl7.org/fhir/StructureDefinition/Patient',
              'http://hl7.org/fhir/StructureDefinition/RelatedPerson',
            ],
            targetResource: ['PractitionerRole', 'Practitioner', 'Organization', 'Device', 'Patient', 'RelatedPerson'],
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: true,
          isResourceType: false,
          isModifier: false,
          isSummary: true,
        },
        {
          path: 'AuditEvent.source.type',
          fieldName: 'type',
          fieldIdentifierName: 'type_',
          short: 'The type of source where event originated',
          definition: 'Code specifying the type of source where event originated.',
          requirements:
            'This field indicates which type of source is identified by the Audit Source ID. It is an optional value that may be used to group events for analysis according to the type of source where the event occurred.',
          min: 0,
          max: '*',
          cardinality: '0..*',
          isRequired: false,
          isArray: true,
          isOptionalItem: false,
          isOptionalList: true,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'Coding',
            code: 'Coding',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: true,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
      ],
      fhirCoreImports: [
        'BackboneElement',
        'FhirDataTypeParser',
        'FhirError',
        'IBase',
        'INSTANCE_EMPTY_ERROR_MSG',
        'JSON',
        'REQUIRED_PROPERTIES_DO_NOT_EXIST',
        'REQUIRED_PROPERTIES_REQD_IN_JSON',
        'StringType',
        'assertFhirType',
        'assertFhirTypeList',
        'assertIsDefined',
        'copyListValues',
        'fhirString',
        'fhirStringSchema',
        'getPrimitiveTypeJson',
        'isDefined',
        'isDefinedList',
        'isElementEmpty',
        'isEmpty',
        'parseFhirPrimitiveData',
        'parseStringType',
        'setFhirComplexJson',
        'setFhirComplexListJson',
        'setFhirPrimitiveJson',
      ],
      generatedImports: ['Coding', 'PARSABLE_DATATYPE_MAP', 'Reference', 'ReferenceTargets'],
    },
    {
      parentUrl: 'http://hl7.org/fhir/StructureDefinition/AuditEvent',
      parentName: 'AuditEvent',
      parentType: 'AuditEvent',
      parentKind: 'resource',
      parentFieldName: 'AuditEvent.entity',
      componentName: 'AuditEventEntityComponent',
      baseDefinitionType: 'BackboneElement',
      isComponentResource: false,
      isComponentDomainResource: false,
      isComponentBackboneElement: true,
      isComponentBackboneType: false,
      isComponentDataType: false,
      isComponentElement: false,
      hasParsableDataType: true,
      rootElement: {
        path: 'AuditEvent.entity',
        componentName: 'AuditEventEntityComponent',
        componentLevel: 2,
        short: 'Data or objects used',
        definition: 'Specific instances of data or objects that have been accessed.',
        comment:
          'Required unless the values for event identification, agent identification, and audit source identification are sufficient to document the entire auditable event. Because events may have more than one entity, this group can be a repeating set of values.',
        requirements: 'The event may have other entities involved.',
        typeCode: 'BackboneElement',
      },
      numRequiredFields: 0,
      hasRequiredFields: false,
      hasResourceFields: false,
      hasPrimitiveFields: true,
      hasOnlyOnePrimitiveField: false,
      hasChoiceFields: false,
      hasCodeSystemEnums: false,
      requiredConstructor: false,
      elementDefinitions: [
        {
          path: 'AuditEvent.entity.what',
          fieldName: 'what',
          fieldIdentifierName: 'what',
          short: 'Specific instance of resource',
          definition: 'Identifies a specific instance of the entity. The reference should be version specific.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'Reference',
            code: 'Reference',
            targetProfile: ['http://hl7.org/fhir/StructureDefinition/Resource'],
            targetResource: ['Resource'],
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: true,
          isResourceType: false,
          isModifier: false,
          isSummary: true,
        },
        {
          path: 'AuditEvent.entity.type',
          fieldName: 'type',
          fieldIdentifierName: 'type_',
          short: 'Type of entity involved',
          definition: 'The type of the object that was involved in this audit event.',
          comment: "This value is distinct from the user\\'s role or any user relationship to the entity.",
          requirements:
            'To describe the object being acted upon. In addition to queries on the subject of the action in an auditable event, it is also important to be able to query on the object type for the action.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'Coding',
            code: 'Coding',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: true,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.entity.role',
          fieldName: 'role',
          fieldIdentifierName: 'role',
          short: 'What role the entity played',
          definition: 'Code representing the role the entity played in the event being audited.',
          requirements:
            'For some detailed audit analysis it may be necessary to indicate a more granular type of entity, based on the application role it serves.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'Coding',
            code: 'Coding',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: true,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.entity.lifecycle',
          fieldName: 'lifecycle',
          fieldIdentifierName: 'lifecycle',
          short: 'Life-cycle stage for the entity',
          definition: 'Identifier for the data life-cycle stage for the entity.',
          comment: 'This can be used to provide an audit trail for data, over time, as it passes through the system.',
          requirements:
            'Institutional policies for privacy and security may optionally fall under different accountability rules based on data life cycle. This provides a differentiating value for those cases.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'Coding',
            code: 'Coding',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: true,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.entity.securityLabel',
          fieldName: 'securityLabel',
          fieldIdentifierName: 'securityLabel',
          short: 'Security labels on the entity',
          definition: 'Security labels for the identified entity.',
          comment: 'Copied from entity meta security tags.',
          requirements:
            'This field identifies the security labels for a specific instance of an object, such as a patient, to detect/track privacy and security issues.',
          min: 0,
          max: '*',
          cardinality: '0..*',
          isRequired: false,
          isArray: true,
          isOptionalItem: false,
          isOptionalList: true,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'Coding',
            code: 'Coding',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: true,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.entity.name',
          fieldName: 'name',
          fieldIdentifierName: 'name',
          short: 'Descriptor for entity',
          definition: 'A name of the entity in the audit event.',
          comment:
            'This field may be used in a query/report to identify audit events for a specific person.  For example, where multiple synonymous entity identifiers (patient number, medical record number, encounter number, etc.) have been used.',
          requirements: "Use only where entity can\\'t be identified with an identifier.",
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'string',
            code: 'StringType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: true,
        },
        {
          path: 'AuditEvent.entity.description',
          fieldName: 'description',
          fieldIdentifierName: 'description',
          short: 'Descriptive text',
          definition: 'Text that describes the entity in more detail.',
          requirements: "Use only where entity can\\'t be identified with an identifier.",
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'string',
            code: 'StringType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.entity.query',
          fieldName: 'query',
          fieldIdentifierName: 'query',
          short: 'Query parameters',
          definition: 'The query parameters for a query-type entities.',
          comment:
            'The meaning and secondary-encoding of the content of base64 encoded blob is specific to the AuditEvent.type, AuditEvent.subtype, AuditEvent.entity.type, and AuditEvent.entity.role.  The base64 is a general-use and safe container for event specific data blobs regardless of the encoding used by the transaction being recorded.  An AuditEvent consuming application must understand the event it is consuming and the formats used by the event. For example, if auditing an Oracle network database access, the Oracle formats must be understood as they will be simply encoded in the base64binary blob.',
          requirements:
            'For query events, it may be necessary to capture the actual query input to the query process in order to identify the specific event. Because of differences among query implementations and data encoding for them, this is a base 64 encoded data blob. It may be subsequently decoded or interpreted by downstream audit analysis processing.',
          min: 0,
          max: '1',
          cardinality: '0..1',
          isRequired: false,
          isArray: false,
          isOptionalItem: true,
          isOptionalList: false,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'base64Binary',
            code: 'Base64BinaryType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: true,
        },
        {
          path: 'AuditEvent.entity.detail',
          fieldName: 'detail',
          fieldIdentifierName: 'detail',
          short: 'Additional Information about the entity',
          definition: 'Tagged value pairs for conveying additional information about the entity.',
          requirements: 'Implementation-defined data about specific details of the object accessed or used.',
          min: 0,
          max: '*',
          cardinality: '0..*',
          isRequired: false,
          isArray: true,
          isOptionalItem: false,
          isOptionalList: true,
          isRequiredItem: false,
          isRequiredList: false,
          type: {
            fhirDataType: 'BackboneElement',
            code: 'AuditEventEntityDetailComponent',
          },
          isBackboneType: true,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
      ],
      fhirCoreImports: [
        'BackboneElement',
        'Base64BinaryType',
        'FhirDataTypeParser',
        'IBase',
        'INSTANCE_EMPTY_ERROR_MSG',
        'JSON',
        'StringType',
        'assertFhirType',
        'assertFhirTypeList',
        'copyListValues',
        'fhirBase64Binary',
        'fhirBase64BinarySchema',
        'fhirString',
        'fhirStringSchema',
        'getPrimitiveTypeJson',
        'isDefined',
        'isDefinedList',
        'isElementEmpty',
        'isEmpty',
        'parseBase64BinaryType',
        'parseFhirPrimitiveData',
        'parseStringType',
        'setFhirBackboneElementListJson',
        'setFhirComplexJson',
        'setFhirComplexListJson',
        'setFhirPrimitiveJson',
      ],
      generatedImports: ['Coding', 'PARSABLE_DATATYPE_MAP', 'Reference', 'ReferenceTargets'],
    },
    {
      parentUrl: 'http://hl7.org/fhir/StructureDefinition/AuditEvent',
      parentName: 'AuditEvent',
      parentType: 'AuditEvent',
      parentKind: 'resource',
      parentFieldName: 'AuditEvent.entity.detail',
      componentName: 'AuditEventEntityDetailComponent',
      baseDefinitionType: 'BackboneElement',
      isComponentResource: false,
      isComponentDomainResource: false,
      isComponentBackboneElement: true,
      isComponentBackboneType: false,
      isComponentDataType: false,
      isComponentElement: false,
      hasParsableDataType: true,
      rootElement: {
        path: 'AuditEvent.entity.detail',
        componentName: 'AuditEventEntityDetailComponent',
        componentLevel: 3,
        short: 'Additional Information about the entity',
        definition: 'Tagged value pairs for conveying additional information about the entity.',
        requirements: 'Implementation-defined data about specific details of the object accessed or used.',
        typeCode: 'BackboneElement',
      },
      numRequiredFields: 2,
      hasRequiredFields: true,
      hasResourceFields: false,
      hasPrimitiveFields: true,
      hasOnlyOnePrimitiveField: true,
      hasChoiceFields: true,
      hasCodeSystemEnums: false,
      requiredConstructor: true,
      elementDefinitions: [
        {
          path: 'AuditEvent.entity.detail.type',
          fieldName: 'type',
          fieldIdentifierName: 'type_',
          short: 'Name of the property',
          definition: 'The type of extra detail provided in the value.',
          min: 1,
          max: '1',
          cardinality: '1..1',
          isRequired: true,
          isArray: false,
          isOptionalItem: false,
          isOptionalList: false,
          isRequiredItem: true,
          isRequiredList: false,
          type: {
            fhirDataType: 'string',
            code: 'StringType',
            primitiveJsonType: 'string',
          },
          isBackboneType: false,
          isChoiceType: false,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: true,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
        {
          path: 'AuditEvent.entity.detail.value[x]',
          fieldName: 'value',
          fieldIdentifierName: 'value',
          short: 'Property value',
          definition: 'The  value of the extra detail.',
          comment:
            'The value can be string when known to be a string, else base64 encoding should be used to protect binary or undefined content.  The meaning and secondary-encoding of the content of base64 encoded blob is specific to the AuditEvent.type, AuditEvent.subtype, AuditEvent.entity.type, and AuditEvent.entity.role.  The base64 is a general-use and safe container for event specific data blobs regardless of the encoding used by the transaction being recorded.  An AuditEvent consuming application must understand the event it is consuming and the formats used by the event. For example if auditing an Oracle network database access, the Oracle formats must be understood as they will be simply encoded in the base64binary blob.',
          requirements: 'Should not duplicate the entity value unless absolutely necessary.',
          min: 1,
          max: '1',
          cardinality: '1..1',
          isRequired: true,
          isArray: false,
          isOptionalItem: false,
          isOptionalList: false,
          isRequiredItem: true,
          isRequiredList: false,
          type: {
            fhirDataType: 'CHOICE',
            code: 'DataType',
            choiceTypes: ['string', 'base64Binary'],
            choiceDataTypes: ['StringType', 'Base64BinaryType'],
          },
          isBackboneType: false,
          isChoiceType: true,
          isComplexType: false,
          isEnumCodeType: false,
          isPrimitiveType: false,
          isReferenceType: false,
          isResourceType: false,
          isModifier: false,
          isSummary: false,
        },
      ],
      fhirCoreImports: [
        'BackboneElement',
        'Base64BinaryType',
        'ChoiceDataTypes',
        'ChoiceDataTypesMeta',
        'DataType',
        'FhirDataTypeParser',
        'FhirError',
        'IBase',
        'INSTANCE_EMPTY_ERROR_MSG',
        'InvalidTypeError',
        'JSON',
        'PrimitiveType',
        'REQUIRED_PROPERTIES_DO_NOT_EXIST',
        'REQUIRED_PROPERTIES_REQD_IN_JSON',
        'StringType',
        'assertFhirType',
        'assertIsDefined',
        'fhirString',
        'fhirStringSchema',
        'getPrimitiveTypeJson',
        'isDefined',
        'isElementEmpty',
        'isEmpty',
        'parseFhirPrimitiveData',
        'parseStringType',
        'setFhirPrimitiveJson',
        'setPolymorphicValueJson',
      ],
      generatedImports: ['PARSABLE_DATATYPE_MAP'],
    },
  ],
  fhirCoreImports: [
    'BackboneElement',
    'Base64BinaryType',
    'BooleanType',
    'ChoiceDataTypes',
    'ChoiceDataTypesMeta',
    'CodeType',
    'DataType',
    'FhirDataTypeParser',
    'FhirError',
    'IBase',
    'INSTANCE_EMPTY_ERROR_MSG',
    'InstantType',
    'InvalidTypeError',
    'JSON',
    'PrimitiveType',
    'PrimitiveTypeJson',
    'REQUIRED_PROPERTIES_DO_NOT_EXIST',
    'REQUIRED_PROPERTIES_REQD_IN_JSON',
    'StringType',
    'UriType',
    'assertFhirType',
    'assertFhirTypeList',
    'assertIsDefined',
    'assertIsDefinedList',
    'copyListValues',
    'fhirBase64Binary',
    'fhirBase64BinarySchema',
    'fhirBoolean',
    'fhirBooleanSchema',
    'fhirCode',
    'fhirCodeSchema',
    'fhirInstant',
    'fhirInstantSchema',
    'fhirString',
    'fhirStringSchema',
    'fhirUri',
    'fhirUriSchema',
    'getPrimitiveTypeJson',
    'getPrimitiveTypeListJson',
    'isDefined',
    'isDefinedList',
    'isElementEmpty',
    'isEmpty',
    'parseBase64BinaryType',
    'parseBooleanType',
    'parseCodeType',
    'parseFhirPrimitiveData',
    'parseInstantType',
    'parseStringType',
    'parseUriType',
    'setFhirBackboneElementJson',
    'setFhirBackboneElementListJson',
    'setFhirComplexJson',
    'setFhirComplexListJson',
    'setFhirPrimitiveJson',
    'setFhirPrimitiveListJson',
    'setPolymorphicValueJson',
  ],
  generatedImports: [
    'CodeableConcept',
    'Coding',
    'DomainResource',
    'FhirResourceParser',
    'FhirResourceType',
    'PARSABLE_DATATYPE_MAP',
    'Period',
    'Reference',
    'ReferenceTargets',
  ],
} as HbsStructureDefinition;
